name: Deploy to develop branch

on:
  push:
    branches: [develop]

jobs:
  deploy-to-production:
    uses: ./.github/workflows/deploy-to-published-theme.yml
    secrets: inherit
    with:
      environment: production

  deploy-to-tagged-themes:
    uses: ./.github/workflows/deploy-to-tagged-themes.yml
    secrets: inherit
    with:
      environment: production